### ISSUE TITLE
Option to include bundle_path to target paths

### ISSUE THREAD

**Issue by iberianpig** [riseshia/oneshot_coverage#6]
## Background
  - We want to stop using the old Gem which we have maintained. 
  -  However, the Gem dynamically adds methods to the model class, which may break our Rails application if Gem is removed.

## Problem
  - The oneshot_coverage Gem is designed to ignore the bundler path. 
  - So that it impossible to track code that the Gem dynamically defines.

I've created a pull request. Please check it out. https://github.com/riseshia/oneshot_coverage/pull/7

**Comment by riseshia** [comment]
Added on 0.4.0~ https://rubygems.org/gems/oneshot_coverage/versions/0.4.0
